sudo: false
dist: trusty
language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.15.1
os:
  - linux
  - osx
cache: cargo
matrix:
  allow_failures:
    - rust: nightly

before_install:
  - git submodule update --init --recursive

script:
  # 1.15 doesn't yet support cargo build --all
  - cd imgui-sys && cargo build --verbose && cd ..
  - cd imgui-glium-renderer && cargo build --verbose && cd ..
  - cargo build --verbose
  - cargo test --all --verbose
