[package]
name = "imgui-sys"
version = "0.0.13"
authors = ["Joonas Javanainen <joonas.javanainen@gmail.com>"]
description = "Raw ocornut/imgui bindings for Rust"
homepage = "https://github.com/gekkio/imgui-rs"
repository = "https://github.com/gekkio/imgui-rs"
license = "MIT OR Apache-2.0"
categories = ["gui", "external-ffi-bindings"]
build = "build.rs"

[dependencies]
bitflags = "0.8"
glium = { version = "0.16", default-features = false, optional = true }

[build-dependencies]
gcc = "0.3"
